### ISSUE TITLE
"This should not ever happen"-errors actually happen

### ISSUE THREAD

**Issue by Martijn02** [isaacs/st#49] opened 2014-09-01 12:03 UTC
I'm seeing these errors in a production environment. I cannot reproduce them in my development environment, so I assume they only happen under a certain amount of load.

I'm trying to find a workaround for this problem, but I have a hard time figuring out how to do so. Can I safely catch this error? or will it leave my app in a strange state? Any help I can get is much appreciated. 

```
/var/www/node_modules/st/st.js:572
  throw new Error('This should not ever happen')
        ^
Error: This should not ever happen
    at Mount._loadContent (/var/www/node_modules/st/st.js:572:9)
    at AsyncCache.get (/var/www/node_modules/st/node_modules/async-cache/ac.js:48:8)
    at Mount.cachedFile (/var/www/node_modules/st/st.js:379:22)
    at Mount.file (/var/www/node_modules/st/st.js:369:10)
    at Mount.<anonymous> (/var/www/node_modules/st/st.js:305:16)
    at /var/www/node_modules/st/node_modules/async-cache/ac.js:58:7
    at Array.forEach (native)
    at AsyncCache.<anonymous> (/var/www/node_modules/st/node_modules/async-cache/ac.js:57:9)
    at Mount.<anonymous> (/var/www/node_modules/st/st.js:561:7)
    at Object.oncomplete (fs.js:107:15)
worker 8483 died
error: Forever detected script exited with code: 1
```

I'm running st (0.5.1) as a piece of express (3.3.1) middleware, 

st is included as follows (showing only relevant portions of my app):

```
if (cluster.isMaster) {
    // Fork workers.
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on('exit', function(worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
        process.exit(1);
    });

} else {

    var app = express();
    app.set('port', process.env.PORT || config.port);
    app.enable('trust proxy');

    app.use(st({
        url: '/',
        path: path.resolve(__dirname, 'public'),
        index: 'index.html',
        passthrough: true
    }));
    app.use(app.router);

    /* Removed custom functions for readability */

    http.createServer(app).listen(app.get('port'), function() {
        console.log('Listening for market %s on port %s', market, app.get('port'));
    });
}

```

**Comment by ArtskydJ** [comment] 2015-05-18 13:30
I got the same error when running `st` from `package.json` scripts.

```json
"scripts": {
  "start": "nohup st -p 1020 -i 'index.html' &"
}
```

**Comment by ArtskydJ** [comment] 2015-05-20 13:09
I added some debug logging [here](https://github.com/ArtskydJ/st/commit/0d5fec1b6c3d8c921dd1f7aebcc62efe1f71b0c4) and [here](https://github.com/ArtskydJ/st/commit/9a05d62e46b52d08ab50d82ed9c2cd08fc8f0bc0) to my `st` fork, and got this result:

```
has: 644:"64769-1192979-1428173090000"

/root/st/st.js:584
  throw new Error('This should not ever happen' +
        ^
Error: This should not ever happen
cache: undefined
key: 644:"64769-1192979-1428173090000"
has: false
expected: undefined, ?, true
```
[See full debug file here](https://github.com/ArtskydJ/lmnpmtfy.com/blob/master/nohup2.txt#L87-L96)

It looks like it is first cached, but in the error it says it is not cached. Maybe a race condition?

**Comment by jamie-green** [comment] 2017-03-22 09:51
Looks like a cached file can be removed from cache between the `if (this.cache.content.has(key))` check in st.js:376 and the actual cache fetch in `Mount.prototype.cachedFile`. I can reproduce this on every request for a cached resource by introducing a delay longer than the cache duration between the check and fetch.

I've yet to find a clean way around this, but guess the options are replacing the check with an actual fetch and handling content / no content, or adding logic to populate the cache in `Mount.prototype._loadContent`.

**Comment by jamie-green** [comment] 2017-03-22 13:38
I now see the issue with both of my suggested approaches: Skipping the check eliminates the race condition but would still require code to populate the cache, so that doesn't help at all. As for populating the cache via `Mount.prototype._loadContent`, the key doesn't contain the path to the file, so we'd need a way to pass that through (probably as part of the key).

**Comment by rvagg** [comment] 2019-11-11 22:52
closing due to age

**Closed by rvagg** 2019-11-11 22:52 UTC
